############################################################
##Pages config
############################################################
#
#############################
## --- Required options --- #
#############################
theme: minima

layout: home
#
# Name of website
title: Technology Hub Wiki
#
# Your name to show in the footer
author: Igor Molchanov

